name: Snyk .NET Scan

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  snyk-dotnet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore all .sln and .csproj files
        run: |
          set -e
          shopt -s globstar nullglob
          for sln in **/*.sln; do
            echo "Restoring solution $sln"
            dotnet restore "$sln"
          done
          for csproj in **/*.csproj; do
            if ! grep -q "$(basename "$csproj")" **/*.sln 2>/dev/null; then
              echo "Restoring standalone project $csproj"
              dotnet restore "$csproj"
            fi
          done

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      - name: Run Snyk test for all .sln and .csproj files
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          mkdir -p snyk-dotnet-results
          shopt -s globstar nullglob
          found=0
          for file in **/*.sln **/*.csproj; do
            if [[ -f "$file" ]]; then
              found=1
              dir=$(dirname "$file")
              base=$(basename "$file")
              echo "Scanning $file"
              (
                cd "$dir" && \
                snyk test --file="$base" --json > "../../snyk-dotnet-results/${base}.snyk.json"
              ) || true
            fi
          done
          if [ $found -eq 0 ]; then
            echo "No .sln or .csproj files found!"
            exit 0
          fi

      - name: Upload Snyk .NET scan results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: snyk-dotnet-results
          path: snyk-dotnet-results/
