name: Snyk Node.js Scan

on:
  workflow_dispatch:

jobs:
  snyk-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node.js dependencies
        run: |
          find . -name package.json -not -path "*/node_modules/*" -execdir npm install \;

      - name: Install Snyk
        run: npm install -g snyk

      - name: Snyk Auth
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      - name: Run Snyk test for all package.json files
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          mkdir -p snyk-node-results
          found=0
          for file in $(find . -name package.json -not -path "*/node_modules/*"); do
            found=1
            echo "Scanning $file"
            snyk test --file="$file" --json > "snyk-node-results/$(basename $(dirname "$file"))-package.snyk.json" || true
          done
          if [ $found -eq 0 ]; then
            echo "No package.json files found!"
            exit 0
          fi

      - name: Upload Snyk Node.js scan results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: snyk-node-results
          path: snyk-node-results/
