name: Example workflow for dotNET using Snyk

on:
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'  # or the version you are using

      - name: Restore dependencies
        run: dotnet restore ./MiniProfiler.sln

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --json-file-output=snyk.json

      - name: Upload Snyk .NET scan results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: snyk-results
          path: snyk.json
